---
version: "3"

tasks:
  default:
    cmds:
      - task --list
  pretty:
    desc: fix errors
    cmds:
      - prettier --parser=markdown --write '*.md' '**/*.md' || true
      - prettier --parser=yaml --write '*.y*ml' '**/*.y*ml' || true
  install-fisher:
    preconditions:
     - bash: command -v "fish" >/dev/null 2>&1 ||
       msg: "fish isn't installed"
    desc: install fisher
    cmds:
      - curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
  install-fisher-third-party:
    desc: install fish third party plugins
    cmds:
      - fish -c "fisher install danhper/fish-ssh-agent"
      - fish -c "fisher install decors/fish-colored-man"
      - fish -c "fisher install edc/bass"
      - fish -c "fisher install evanlucas/fish-kubectl-completions"
      - fish -c "fisher install franciscolourenco/done"
      - fish -c "fisher install jethrokuan/z"
      - fish -c "fisher install jorgebucaran/spark.fish"
      - fish -c "fisher install oh-my-fish/plugin-bang-bang"
      - fish -c "fisher install patrickf3139/fzf.fish"
      - fish -c "fisher install wfxr/forgit"
  install-vim-plug:
    preconditions:
     - bash: command -v "curl" >/dev/null 2>&1 ||
       msg: "curl isn't installed"
    desc: install latest vundle
    cmds:
      - curl -fLo ~/.config/.nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  install-tpm:
    preconditions:
     - bash: command -v "git" >/dev/null 2>&1 ||
       msg: "git isn't installed"
    desc: install latest tpm
    cmds:
      - git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
      - tmux source-file ~/.tmux.conf
      - ~/.tmux/plugins/tpm/bin/install_plugins
  update-tpm:
    preconditions:
     - bash: command -v "tmux" >/dev/null 2>&1 ||
       msg: "git isn't installed"
    desc: update tpm and it's plugins
    cmds:
      - git -C ~/.tmux/plugins/tpm config pull.rebase true
      - git -C ~/.tmux/plugins/tpm pull
