#!/bin/bash
if [ -f /run/.containerenv ]; then
    podman-remote run --rm -it --entrypoint=jira -v ~/.netrc:/root/.netrc -v ~/.config/.jira:/root/.config/.jira ghcr.io/ankitpokhrel/jira-cli:latest "$@"
else 
    podman run --rm -it --entrypoint=jira -v ~/.netrc:/root/.netrc -v ~/.config/.jira:/root/.config/.jira ghcr.io/ankitpokhrel/jira-cli:latest "$@"
fi

