#!/bin/bash
if [ -f /run/.containerenv ]; then
    podman-remote run --rm -it -e JIRA_AUTH_TYPE=bearer \
      -e JIRA_API_TOKEN=$JIRA_API_TOKEN \
      --entrypoint=jira -v ~/.netrc:/root/.netrc:z \
      -v ~/.config/.jira/:/root/.config/.jira/:z ghcr.io/ankitpokhrel/jira-cli:latest "$@"
else 
    podman run --rm -it -e JIRA_AUTH_TYPE=bearer \
      -e JIRA_API_TOKEN=$JIRA_API_TOKEN \
      --entrypoint=jira -v ~/.netrc:/root/.netrc:z \
      -v ~/.config/.jira/:/root/.config/.jira/:z ghcr.io/ankitpokhrel/jira-cli:latest "$@"
fi

