#!/bin/bash
if [ -f /run/.containerenv ]; then
    podman-remote run --rm -v "$(pwd)":/data -t ghcr.io/terraform-linters/tflint:latest "$@"
else 
    podman run --rm -v "$(pwd)":/data -t ghcr.io/terraform-linters/tflint:latest "$@"
fi

