add_newline = true

[character]
success_symbol = "\n[❯](bold green)"
error_symbol = "\n[✖](bold red)"

[cmd_duration]
format = '\[[⏱ $duration ]($style)\]'

[directory]
truncation_length = 5
truncate_to_repo = true

[username]
show_always = false

[aws]
format = 'on [$symbol$profile( $region)]($style) '
style = 'bold Yellow'
symbol = '☁️ '

[aws.region_aliases]
us-east-1 = 'N. Virginia'
us-east-2 = 'Ohio'
us-west-1 = 'N. California'
us-west-2 = 'Oregon'

[kubernetes]
symbol = 'ﴱ '
format = 'on [ﴱ $context \($namespace\)](bold bright-green) '
disabled = false

[git_branch]
symbol = ' '

